# Generated by Django 5.1.7 on 2025-03-11 12:23

import quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='code',
            field=models.CharField(default=quizzes.models.generate_unique_code, max_length=10, unique=True),
        ),
    ]
