# Generated by Django 5.1.7 on 2025-03-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_question_time_limit_remove_quiz_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='time_taken',
            field=models.IntegerField(default=0, help_text='Total time taken in seconds'),
        ),
    ]
