# Generated by Django 5.1.7 on 2025-03-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_participation_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='minimum_score_percentage',
            field=models.IntegerField(default=60, help_text='Minimum score required to pass (%)'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
