# Generated by Django 5.1.7 on 2025-03-17 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_quiz_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='participation',
            name='total_time_taken',
            field=models.IntegerField(default=0, help_text='Total time taken for the quiz in seconds'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.IntegerField(default=0, help_text='Time taken for this question in seconds')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.participation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.option')),
            ],
        ),
    ]
