# Generated by Django 5.1.7 on 2025-03-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_rename_time_limit_per_question_quiz_time_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='time_limit',
            new_name='time_limit_per_question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time_limit_type',
        ),
    ]
