# Generated by Django 5.1.7 on 2025-03-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_rename_time_limit_quiz_time_limit_per_question_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='participation',
            name='attempt_number',
            field=models.IntegerField(default=1, help_text='The attempt number for this user on this quiz'),
        ),
    ]
