# Generated by Django 5.1.7 on 2025-03-17 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_alter_participation_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'quiz')},
        ),
        migrations.AddField(
            model_name='participation',
            name='attempts',
            field=models.IntegerField(default=0, help_text='Number of times the user has taken this quiz'),
        ),
        migrations.RemoveField(
            model_name='participation',
            name='attempt_number',
        ),
    ]
