# Generated by Django 5.1.7 on 2025-03-18 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_alter_participation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='attempts',
        ),
    ]
