# Generated by Django 5.1.7 on 2025-03-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_remove_participation_attempts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='participation',
            name='attempt_number',
            field=models.IntegerField(default=1, help_text='The attempt number for this user on this quiz'),
        ),
    ]
